apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-app-deployment
  # namespace: production

spec:
  replicas: 2
  

  selector:
    matchLabels:
      app: python-app

  template:
    metadata:
      labels:
        app: python-app
      
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"

    spec:
      containers:
        - name: python-app

          image: 533267054305.dkr.ecr.us-east-1.amazonaws.com/python-app

          env:
            - name: env
              value: prod
              
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          envFrom:
          - secretRef:
              name: postgres-secret