FROM python:3.10-slim AS builder
WORKDIR /app
COPY application/requirements.txt .
RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt
COPY application/app.py .

FROM python:3.10-slim 
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /app/app.py .
EXPOSE 5000 
ENTRYPOINT ["python"]
CMD ["app.py"]
